USE MMSPlus

ALTER TABLE DIVISION_SETTINGS ADD ACCOUNT_NO VARCHAR(50) null 
ALTER TABLE DIVISION_SETTINGS ADD BANK_NAME VARCHAR(70) null 
ALTER TABLE DIVISION_SETTINGS ADD BRANCH_ADDRESS VARCHAR(250) null 
ALTER TABLE DIVISION_SETTINGS ADD IFSC_CODE VARCHAR(50) null 
ALTER TABLE DIVISION_SETTINGS ADD AUTH_SIGNATORY VARCHAR(80) null 

-----------------------------------

USE AdminPlus

ALTER TABLE DIVISION_MASTER ADD ACCOUNT_NO VARCHAR(50) null 
ALTER TABLE DIVISION_MASTER ADD BANK_NAME VARCHAR(70) null 
ALTER TABLE DIVISION_MASTER ADD BRANCH_ADDRESS VARCHAR(250) null 
ALTER TABLE DIVISION_MASTER ADD IFSC_CODE VARCHAR(50) null 
ALTER TABLE DIVISION_MASTER ADD AUTH_SIGNATORY VARCHAR(80) null 