USE MMSPlus

ALTER TABLE SALE_INVOICE_MASTER ADD TRANSPORT VARCHAR(50) null

ALTER TABLE DIVISION_SETTINGS ADD ACCOUNT_NO VARCHAR(50) null 
ALTER TABLE DIVISION_SETTINGS ADD BANK_NAME VARCHAR(70) null 
ALTER TABLE DIVISION_SETTINGS ADD BRANCH_ADDRESS VARCHAR(250) null 
ALTER TABLE DIVISION_SETTINGS ADD IFSC_CODE VARCHAR(50) null 
ALTER TABLE DIVISION_SETTINGS ADD AUTH_SIGNATORY VARCHAR(80) null 

-----------------------------------

USE AdminPlus

ALTER TABLE DivisionMaster ADD ACCOUNT_NO VARCHAR(50) null 
ALTER TABLE DivisionMaster ADD BANK_NAME VARCHAR(70) null 
ALTER TABLE DivisionMaster ADD BRANCH_ADDRESS VARCHAR(250) null 
ALTER TABLE DivisionMaster ADD IFSC_CODE VARCHAR(50) null 
ALTER TABLE DivisionMaster ADD AUTH_SIGNATORY VARCHAR(80) null 